orchestrator:
  host: localhost
  port: 8085
detectors:
  - name: regex-language
    input: false
    output: true
    detector_params:
      regex:
        - email
        - ssn
routes:
  - name: pii
    detectors:
      - regex-language
    fallback_message: "I'm sorry, I'm afraid I can't do that."
  - name: passthrough
    detectors:
