orchestrator:
  host: guardrails-orchestrator-http-model-namespace.apps.rosa.trustyai-rob2.n1ai.p3.openshiftapps.com
detectors:
  - name: regex_language
    detector_params:
      regex:
        - email
        - ssn
  - name: other_detector
routes:
  - name: pii
    detectors:
      - regex_language
    fallback_message: "I'm sorry Dave, I'm afraid I can't do that."
  - name: passthrough
    detectors:
